# Configuration des urls
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

# LOGGING
logging:
  file:
    path: /var/log
    name: publicenemy/publicenemy.log
    maxHistory: 365
  level:
    root: WARN
    org:
      springframework:
        boot: INFO
      hibernate:
        SQL: ERROR
    fr:
      insee:
        publicenemy: INFO

spring:
  # DB
  datasource:
    url: jdbc:postgresql://localhost:53941/public-enemy
    username: stromae
    password: stromaePassword
    hikari.maximumPoolSize: 5
  # LIQUIBASE
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  banner:
    location: banner.txt
  # Uploads
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:
    open-in-view: false
  codec:
    max-in-memory-size: 10000KB
  # to make springfox work
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  debug:
    webclient: false
  proxy:
    enable: false
    url:
    port:
  cors:
    allowed-origins:
  pogues:
    url: https://pogues-url.insee.fr
  queen:
    url: https://queen-url.insee.fr
  eno:
    url: https://eno-url.insee.fr
  questionnaire:
    metadata:
      -
        name: Enq_ObjectifsCourts
        value: Cette enquête permet de connaître l'équipement et les usages des personnes dans le domaine des technologies de l'information et de la communication (téléphone fixe et mobile, informatique, internet sur support fixe et mobile).
      -
        name: Enq_MinistereTutelle
        value: de l'Économie, des Finances et de la Relance
      -
        name: Enq_RespOperationnel
        value: L’Institut national de la statistique et des études économiques (Insee)
      -
        name: Enq_RespTraitement
        value: l'Insee
      -
        name: Loi_statistique
        value: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000888573
      -
        name: Loi_rgpd
        value: https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX%3A32016R0679
      -
        name: Loi_informatique
        value: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000886460

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: db, diskSpace
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true